PharmaApp/PharmaWeb/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PharmaWeb.Controllers
{
    public class LogoutController : Controller
    {
        // GET: Logout
        public ActionResult Index()
        {

            Session["user"] = null;
            return RedirectToAction("Index","Login");
        }
    }
}

PharmaApp/PharmaWeb/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PharmaWeb.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }
    }
}

PharmaApp/PharmaWeb/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Content/img/pharmacy.ico"/>
    <title>@ViewBag.Title - PharmaApp</title>
    @Styles.Render("~/Content/home")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar-wrapper">
        <div class="container">

            <nav class="navbar navbar-default navbar-static-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("PharmaApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Medicament<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Afficher", "Index", "Medicament")</li>
                                    <li>@Html.ActionLink("Ajouter", "Add", "Medicament")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Famille<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Afficher", "Index", "Famille")</li>
                                    <li>@Html.ActionLink("Ajouter", "Add", "Famille")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Stock", "Index", "Stock")</li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vente<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Afficher", "Index", "Vente")</li>
                                    <li>@Html.ActionLink("Ajouter", "Add", "Vente")</li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Utilisateur<span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Afficher", "Index", "User")</li>
                                    <li>@Html.ActionLink("Ajouter", "Add", "User")</li>
                                </ul>
                            </li>
                            <li>@Html.ActionLink("Recherche", "Index", "Search")</li>
                            <li>@Html.ActionLink("Deconnection", "Index", "Logout")</li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
        @RenderBody()
        <hr style="color:#378608"/>
        <footer>
            <p class="col-sm-12 text-center">&copy; @DateTime.Now.Year - PharmaApp par Brahim Baheida & Mohamed Sidatt & Nehah Sidi Mohamed</p>
        </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PharmaApp/PharmaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Content/img/pharmacy.ico"/>
    <title>@ViewBag.Title - PharmaApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PharmaApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Medicament<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Afficher", "Index", "Medicament")</li>
                            <li>@Html.ActionLink("Ajouter", "Add", "Medicament")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Famille<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Afficher", "Index", "Famille")</li>
                            <li>@Html.ActionLink("Ajouter", "Add", "Famille")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Stock", "Index", "Stock")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vente<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Afficher", "Index", "Vente")</li>
                            <li>@Html.ActionLink("Ajouter", "Add", "Vente")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Utilisateur<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Afficher", "Index", "User")</li>
                            <li>@Html.ActionLink("Ajouter", "Add", "User")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Recherche", "Index", "Search")</li>
                    <li>@Html.ActionLink("Deconnection", "Index", "Logout")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr style="border:green ridge" />
        <footer>
            <p class="col-sm-12 text-center"><b>&copy; @DateTime.Now.Year - PharmaApp par Brahim Baheida & Mohamed Sidatt & Nehah Sidi Mohamed</b></p>
        </footer>
    </div>
   

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>

PharmaApp/PharmaWeb/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/Content/img/pharmacy.ico" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/style")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - PharmaApp par Brahim Baheida & Mohamed Sidatt & Nehah Sidi Mohamed</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>